name: Attach Artifact to Release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main

jobs:
  attach-artifact-to-release:
    uses: liquibase/build-logic/.github/workflows/extension-attach-artifact-release.yml@DAT-17770
    secrets: inherit
    with:
      extraCommand: mvn install:install-file -Dfile=lib/GoogleBigQueryJDBC42.jar -DgroupId=com.simba.googlebigquery.jdbc -DartifactId=GoogleBigQueryJDBC42 -Dversion=4.2 -Dpackaging=jar
