name: Attach Artifact to Release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
  push:
    branches:
      - main
# test2
jobs:
  attach-artifact-to-release:
    uses: liquibase/build-logic/.github/workflows/extension-attach-artifact-release.yml@DAT-18547
    secrets: inherit
