name: 'Continuous Integration - Report'
on:
  workflow_run:
    workflows: [Continuous Integration]
    types: [completed]

jobs:
  test-report:
    uses: liquibase/build-logic/.github/workflows/ci-report.yml@v0.4.4
    secrets: inherit