name: Continuous Integration

# Job will run nightly at 02:05 EDT / 01:05 CDT
# Time below is UTC
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: "5 6 * * *"
  push:
    branches:
      - main

jobs:
  build:
    uses: liquibase/build-logic/.github/workflows/ci.yml@v0.4.4
    secrets: inherit