name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    uses: liquibase/build-logic/.github/workflows/create-release.yml@v0.7.8
    secrets: inherit
    with:
      extraCommand: mvn install:install-file -Dfile=lib/GoogleBigQueryJDBC42.jar -DgroupId=com.simba.googlebigquery.jdbc -DartifactId=GoogleBigQueryJDBC42 -Dversion=4.2 -Dpackaging=jar
